### PR TITLE
demo: enable nfs on the master so that asb launches

### PR DESCRIPTION
**Pull request by karmab**
Signed-off-by: karimb <karimboumedhel@gmail.com>

### CODE REVIEW

**Comment by karmab** [comment]
tested successfully those parameters on my own setup

**Review by rmohr — APPROVED** [review]

**Comment by rmohr** [comment]
@karmab is that a prerequisite so that the broker gets started? What exactly does the broker need the nfs store for?

**Comment by rmohr** [comment]
@karmab will you also add a role which will pull in the apb which you are working on?

**Comment by karmab** [comment]
technically, my apb lives in the [ansibleplaybookbundle](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=ansibleplaybookbundle&starCount=0) org, which is enabled by default when you deploy ansible service broker, so no additional changes are needed

**Pull request merged**
